service: ag16-stats
useDotenv: true
variablesResolutionMode: 20210326
frameworkVersion: ^2.32.1

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: eu-west-1

  environment: # Service wide environment variables
    REGION: ${self:provider.region}
    STATS_DATA_TABLE: !Ref AG16Stats

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            Fn::GetAtt:
              - AG16Stats
              - Arn

functions:
  getIoTStats:
    handler: src/getIoTStats.handle
    events:
      - iot:
          sql: "SELECT * FROM 'AG16/stats'"

resources:
  Resources:
    AG16Stats:
      Type: AWS::DynamoDB::Table
      # DeletionPolicy: Retain
      Properties:
        TableName: AG16-stats-${opt:stage, 'dev'}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: time
            AttributeType: "N"
        KeySchema:
          - AttributeName: time
            KeyType: HASH
